from controllers.convert_controller import ConvertController
from controllers.currency_controller import CurrencyController
from controllers.rate_controller import RateController
from server_app import Application