INSERT OR IGNORE INTO Currencies (Code, FullName, Sign) VALUES
('AFN','Afghani','؋'),
('ALL','Lek','L'),
('DZD','Algerian Dinar','د.ج'),
('USD','US Dollar','$'),
('EUR','Euro','€'),
('AOA','Kwanza','Kz'),
('XCD','East Caribbean Dollar','$'),
('ARS','Argentine Peso','$'),
('AMD','Armenian Dram','֏'),
('AWG','Aruban Florin','ƒ'),
('AUD','Australian Dollar','A$'),
('AZN','Azerbaijanian Manat','₼'),
('BSD','Bahamian Dollar','$'),
('BHD','Bahraini Dinar','.د.ب'),
('BDT','Taka','৳'),
('BBD','Barbados Dollar','$'),
('BYN','Belarusian Ruble','Br'),
('BZD','Belize Dollar','$'),
('XOF','CFA Franc BCEAO','CFA'),
('BMD','Bermudian Dollar','$'),
('BTN','Ngultrum','Nu.'),
('INR','Indian Rupee','₹'),
('BOB','Boliviano','Bs.'),
('BOV','Mvdol','BOV'),
('BAM','Convertible Mark','KM'),
('BWP','Pula','P'),
('NOK','Norwegian Krone','kr'),
('BRL','Brazilian Real','R$'),
('BND','Brunei Dollar','$'),
('BIF','Burundi Franc','FBu'),
('CVE','Cabo Verde Escudo','$'),
('KHR','Riel','៛'),
('XAF','CFA Franc BEAC','CFA'),
('CAD','Canadian Dollar','C$'),
('KYD','Cayman Islands Dollar','$'),
('CLF','Unidad de Fomento','UF'),
('CLP','Chilean Peso','$'),
('CNY','Yuan Renminbi','¥'),
('COP','Colombian Peso','$'),
('COU','Unidad de Valor Real','COU'),
('KMF','Comoro Franc','CF'),
('CDF','Congolese Franc','FC'),
('NZD','New Zealand Dollar','NZ$'),
('CRC','Costa Rican Colon','₡'),
('CUP','Cuban Peso','$'),
('CUC','Peso Convertible','$'),
('CZK','Czech Koruna','Kč'),
('DKK','Danish Krone','kr'),
('DJF','Djibouti Franc','Fdj'),
('DOP','Dominican Peso','RD$'),
('EGP','Egyptian Pound','£'),
('ETB','Ethiopian Birr','Br'),
('FKP','Falkland Islands Pound','£'),
('FJD','Fiji Dollar','$'),
('XPF','CFP Franc','₣'),
('GMD','Dalasi','D'),
('GEL','Lari','₾'),
('GHS','Ghana Cedi','₵'),
('GIP','Gibraltar Pound','£'),
('GTQ','Quetzal','Q'),
('GBP','Pound Sterling','£'),
('GNF','Guinea Franc','FG'),
('GYD','Guyana Dollar','$'),
('HTG','Gourde','G'),
('HNL','Lempira','L'),
('HKD','Hong Kong Dollar','HK$'),
('HUF','Forint','Ft'),
('ISK','Iceland Krona','kr'),
('IDR','Rupiah','Rp'),
('IRR','Iranian Rial','﷼'),
('IQD','Iraqi Dinar','ع.د'),
('ILS','New Israeli Sheqel','₪'),
('JMD','Jamaican Dollar','$'),
('JPY','Yen','¥'),
('JOD','Jordanian Dinar','د.ا'),
('KZT','Tenge','₸'),
('KES','Kenyan Shilling','Sh'),
('KRW','Won','₩'),
('KWD','Kuwaiti Dinar','د.ك'),
('KGS','Som','с'),
('LAK','Kip','₭'),
('LBP','Lebanese Pound','£'),
('LRD','Liberian Dollar','$'),
('LYD','Libyan Dinar','ل.د'),
('CHF','Swiss Franc','CHF'),
('MOP','Pataca','P'),
('MGA','Malagasy Ariary','Ar'),
('MWK','Kwacha','MK'),
('MYR','Malaysian Ringgit','RM'),
('MVR','Rufiyaa','Rf'),
('MXN','Mexican Peso','$'),
('MDL','Moldovan Leu','L'),
('MNT','Tugrik','₮'),
('MAD','Moroccan Dirham','د.م.'),
('MZN','Mozambique Metical','MT'),
('MMK','Kyat','Ks'),
('NAD','Namibia Dollar','$'),
('NPR','Nepalese Rupee','रू'),
('NGN','Naira','₦'),
('OMR','Rial Omani','ر.ع.'),
('PKR','Pakistan Rupee','₨'),
('PAB','Balboa','B/.'),
('PGK','Kina','K'),
('PYG','Guarani','₲'),
('PEN','Nuevo Sol','S/'),
('PHP','Philippine Peso','₱'),
('PLN','Zloty','zł'),
('QAR','Qatari Rial','ر.ق'),
('RON','Romanian Leu','lei'),
('RUB','Russian Ruble','₽'),
('RWF','Rwanda Franc','FRw'),
('SAR','Saudi Riyal','﷼'),
('RSD','Serbian Dinar','din'),
('SGD','Singapore Dollar','S$'),
('ZAR','Rand','R'),
('SEK','Swedish Krona','kr'),
('THB','Baht','฿'),
('TRY','Turkish Lira','₺'),
('UAH','Hryvnia','₴'),
('AED','UAE Dirham','د.إ'),
('UYU','Peso Uruguayo','$'),
('UZS','Uzbekistan Sum','soʻm'),
('VND','Dong','₫'),
('ZMW','Zambian Kwacha','ZK'),
('ZWL','Zimbabwe Dollar','$');
